version: "3.9"

services:
  backend:
    build: ./fitness-tracker-service
    container_name: fitness-tracker-backend
    ports:
      - "8081:8081"

  frontend:
    build: ./fitness-tracker-web
    container_name: fitness-tracker-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
